"""Initial migration

Revision ID: 3316bc622da1
Revises: 1f61bfbe16e3
Create Date: 2024-12-12 11:35:24.707356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3316bc622da1'
down_revision: Union[str, None] = '1f61bfbe16e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('qr_code_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'qr_code_path')
    # ### end Alembic commands ###
