"""add capacity

Revision ID: c031cc4763d7
Revises: b051eff08c86
Create Date: 2024-12-16 10:51:45.618958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c031cc4763d7'
down_revision: Union[str, None] = 'b051eff08c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('registration_deadline', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'capacity')
    op.drop_column('events', 'registration_deadline')
    # ### end Alembic commands ###
